use std::io::Error;

pub fn run() -> Result<(), Error> {
    Ok(())
}
